=== Gajnavi/UniProject/books.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT books (book+)>
<!ELEMENT book (title, author, published_year, isbn_10, isbn_13, page_count, categories, thumbnail, description)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT published_year (#PCDATA)>
<!ELEMENT isbn_10 (#PCDATA)>
<!ELEMENT isbn_13 (#PCDATA)>
<!ELEMENT page_count (#PCDATA)>
<!ELEMENT categories (category+)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT thumbnail (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== Gajnavi/UniProject/books.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE records SYSTEM "books.dtd">

<books>
  <book id="1">
    <original_query>Frankenstein</original_query>
    <title>Frankenstein</title>
    <authors>Mary Shelley</authors>
    <published_year>2004</published_year>
    <isbn_10>0743487583</isbn_10>
    <isbn_13>9780743487580</isbn_13>
    <page_count>353</page_count>
    <categories>Fiction</categories>
    <thumbnail>http://books.google.com/books/content?id=UL6Cwv2Z1iQC&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;edge=curl&amp;source=gbs_api</thumbnail>
    <description>"Includes detailed explanatory notes, an overview of key themes, and more"--Cover.</description>
  </book>
  <book id="2">
    <original_query>Dracula</original_query>
    <title>Dracula</title>
    <authors>Bram Stoker</authors>
    <published_year>1897</published_year>
    <isbn_10/>
    <isbn_13/>
    <page_count>384</page_count>
    <categories>Fiction</categories>
    <thumbnail>http://books.google.com/books/content?id=T1VDAQAAMAAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;edge=curl&amp;source=gbs_api</thumbnail>
    <description>A naive young Englishman travels to Transylvania to do business with a client, Count Dracula. After showing his true and terrifying colors, Dracula boards a ship for England in search of new, fresh blood. Unexplained disasters begin to occur in the streets of London before the mystery and the evil doer are finally put to rest. Told in a series of news reports from eyewitness observers to writers of personal diaries, this has a ring of believability.</description>
  </book>
  <book id="3">
    <original_query>Norwegian Woods</original_query>
    <title>Norwegian Wood</title>
    <authors>Haruki Murakami</authors>
    <published_year>2001</published_year>
    <isbn_10>1860468187</isbn_10>
    <isbn_13>9781860468186</isbn_13>
    <page_count>389</page_count>
    <categories>Man-woman relationships</categories>
    <thumbnail>http://books.google.com/books/content?id=27KePwAACAAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;source=gbs_api</thumbnail>
    <description>Toru Watanabe is looking back on the love and passions of his life and trying to make sense of it all. As his first love, Naoko, sinks deeper and deeper into mental despair, he is inexorably pushed to find new meanings and new love to survive.</description>
  </book>
  <book id="4">
    <original_query>1984</original_query>
    <title>1984</title>
    <authors>George Orwell</authors>
    <published_year>2014</published_year>
    <isbn_10>1784043737</isbn_10>
    <isbn_13>9781784043735</isbn_13>
    <page_count>361</page_count>
    <categories>Fiction</categories>
    <thumbnail>http://books.google.com/books/content?id=uyr8BAAAQBAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;edge=curl&amp;source=gbs_api</thumbnail>
    <description>George Orwell's dystopian masterpiece, Nineteen Eighty-Four is perhaps the most pervasively influential book of the twentieth century, making famous Big Brother, newspeak and Room 101. 'Who controls the past controls the future: who controls the present controls the past'</description>
  </book>
  <book id="5">
    <original_query>The odyssey</original_query>
    <title>The Odyssey</title>
    <authors>Homer</authors>
    <published_year>1997</published_year>
    <isbn_10>0140268863</isbn_10>
    <isbn_13>9780140268867</isbn_13>
    <page_count/>
    <categories>Poetry</categories>
    <thumbnail>http://books.google.com/books/content?id=An2MEAAAQBAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;source=gbs_api</thumbnail>
    <description>The great epic of Western literature, translated by the acclaimed classicist Robert Fagles A Penguin Classic Robert Fagles, winner of the PEN/Ralph Manheim Medal for Translation and a 1996 Academy Award in Literature from the American Academy of Arts and Letters, presents us with Homer's best-loved and most accessible poem in a stunning modern-verse translation. "Sing to me of the man, Muse, the man of twists and turns driven time and again off course, once he had plundered the hallowed heights of Troy." So begins Robert Fagles' magnificent translation of the Odyssey, which Jasper Griffin in the New York Times Book Review hails as "a distinguished achievement." If the Iliad is the world's greatest war epic, the Odyssey is literature's grandest evocation of an everyman's journey through life. Odysseus' reliance on his wit and wiliness for survival in his encounters with divine and natural forces during his ten-year voyage home to Ithaca after the Trojan War is at once a timeless human story and an individual test of moral endurance. In the myths and legends retold here, Fagles has captured the energy and poetry of Homer's original in a bold, contemporary idiom, and given us an Odyssey to read aloud, to savor, and to treasure for its sheer lyrical mastery. Renowned classicist Bernard Knox's superb introduction and textual commentary provide insightful background information for the general reader and scholar alike, intensifying the strength of Fagles's translation. This is an Odyssey to delight both the classicist and the general reader, to captivate a new generation of Homer's students. This Penguin Classics Deluxe Edition features French flaps and deckle-edged paper. For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators.</description>
  </book>
  <book id="6">
    <original_query>The alchemist</original_query>
    <title>The Alchemist</title>
    <authors>Paulo Coelho</authors>
    <published_year>2015</published_year>
    <isbn_10>0062416219</isbn_10>
    <isbn_13>9780062416216</isbn_13>
    <page_count>166</page_count>
    <categories>Business &amp; Economics</categories>
    <thumbnail>http://books.google.com/books/content?id=FzVjBgAAQBAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;source=gbs_api</thumbnail>
    <description>“To realize one’s destiny is a person’s only obligation.”—from The Alchemist The Alchemist tells the story of Santiago, the young Andalusian shepherd who dreams of buried treasure in Egypt and embarks upon a challenging journey to find it. With all the simplicity and symbolic richness of a fable, Coelho’s novel is both a hunt for buried treasure and a spiritual quest, with a hero who overcomes trials along the way with the help of teachers who guide him. Paulo Coelho’s books have difficult—and valuable—lessons to impart, but much of their appeal comes from the way Coelho dramatizes these lessons. With exquisite simplicity, the author brings to these stories his own experience of confronting life’s most profound challenges, his broad knowledge of philosophy, psychology, and literature, and a deeply-felt humanity. Freshman Common Read: Erskine College, Montana State University at Bozeman, Immaculata University, Queensborough Community College</description>
  </book>
  <book id="7">
    <original_query>by the river pedra i sat down and wept</original_query>
    <title>By the River Piedra I Sat Down and Wept</title>
    <authors>Paulo Coelho</authors>
    <published_year>1997</published_year>
    <isbn_10>0060977264</isbn_10>
    <isbn_13>9780060977269</isbn_13>
    <page_count>196</page_count>
    <categories>Fiction</categories>
    <thumbnail>http://books.google.com/books/content?id=GR7mQc5R0SYC&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;source=gbs_api</thumbnail>
    <description>Pilar, a young scholar feeling hopeless and worn down by the endless cycle of her days, is contacted by a childhood friend who is now a charismatic spiritual leader.</description>
  </book>
  <book id="8">
    <original_query>pride and prejudice</original_query>
    <title>Pride and Prejudice</title>
    <authors>Jane Austen</authors>
    <published_year>1918</published_year>
    <isbn_10/>
    <isbn_13/>
    <page_count>448</page_count>
    <categories>Courtship</categories>
    <thumbnail>http://books.google.com/books/content?id=s1gVAAAAYAAJ&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;source=gbs_api</thumbnail>
    <description>Austen’s most celebrated novel tells the story of Elizabeth Bennet, a bright, lively young woman with four sisters, and a mother determined to marry them to wealthy men. At a party near the Bennets’ home in the English countryside, Elizabeth meets the wealthy, proud Fitzwilliam Darcy. Elizabeth initially finds Darcy haughty and intolerable, but circumstances continue to unite the pair. Mr. Darcy finds himself captivated by Elizabeth’s wit and candor, while her reservations about his character slowly vanish. The story is as much a social critique as it is a love story, and the prose crackles with Austen’s wry wit.</description>
  </book>
  <book id="9">
    <original_query>wuthering heights</original_query>
    <title>Wuthering Heights in Plain and Simple English (Includes Study Guide, Complete Unabridged Book, Historical Context, Biography And</title>
    <authors>Emily Brontë</authors>
    <published_year>2012</published_year>
    <isbn_10>1621074560</isbn_10>
    <isbn_13>9781621074564</isbn_13>
    <page_count>614</page_count>
    <categories>Reference</categories>
    <thumbnail>http://books.google.com/books/content?id=S2Yvf-tWNdUC&amp;printsec=frontcover&amp;img=1&amp;zoom=1&amp;edge=curl&amp;source=gbs_api</thumbnail>
